version: '3'
 
services:
  vs-app:
    image: "shevv920/vs-app"
    ports:
      - "31990:31990"
    depends_on: 
      - "db"
    networks:
      - "vs_app_network"
    command: node src/index.js
  db:
    image: "mongo:4.2"
    container_name: vs_mongo
    ports:
      - "27017:27017"
    volumes:     
      - "dbdata:/data/vs_db"
    networks:
      - "vs_app_network"
    
networks:
  vs_app_network:
  
volumes:
  dbdata:
